import type { PlanElement } from "@/types";

/**
 * ATT&CK Navigator layer export — turns the technique references across all
 * plan elements into a layer-format-4.5 document that mitre-attack/attack-navigator
 * can open. Pure logic (type-only imports) so it is testable in plain Node —
 * see scripts/validate-navigator-layer.mjs.
 */

export interface NavigatorTechniqueEntry {
  techniqueID: string;
  score: number;
  comment: string;
}

export interface NavigatorLayer {
  name: string;
  versions: { attack: string; navigator: string; layer: string };
  domain: "enterprise-attack";
  description: string;
  techniques: NavigatorTechniqueEntry[];
  gradient: { colors: string[]; minValue: number; maxValue: number };
}

/** Count of distinct technique IDs referenced across the plan's elements. */
export function countTechniques(elements: PlanElement[]): number {
  const ids = new Set<string>();
  for (const el of elements) for (const t of el.techniques ?? []) ids.add(t.id);
  return ids.size;
}

/**
 * Build a Navigator layer from the plan. Score = number of elements
 * referencing the technique; comment = the names of those elements.
 * Returns null when the plan references no techniques.
 */
export function buildNavigatorLayer(scenarioName: string, elements: PlanElement[]): NavigatorLayer | null {
  const byTechnique = new Map<string, string[]>(); // techniqueID -> element names
  for (const el of elements) {
    for (const t of el.techniques ?? []) {
      const names = byTechnique.get(t.id) ?? [];
      names.push(el.name);
      byTechnique.set(t.id, names);
    }
  }
  if (byTechnique.size === 0) return null;

  const techniques: NavigatorTechniqueEntry[] = [...byTechnique.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([techniqueID, names]) => ({
      techniqueID,
      score: names.length,
      comment: names.join(", "),
    }));
  const maxScore = Math.max(...techniques.map((t) => t.score));

  return {
    name: `${scenarioName} — techniques`,
    versions: { attack: "19", navigator: "5.1.0", layer: "4.5" },
    domain: "enterprise-attack",
    description: `Techniques referenced by the "${scenarioName}" OAKOC plan. Generated by Chinook Cyber Planner (chinookcyber.com).`,
    techniques,
    gradient: {
      colors: ["#e7efe8", "#58855f"], // pale sand-pine tint → pine (--accent-primary)
      minValue: 0,
      maxValue: maxScore,
    },
  };
}

/** Filesystem-safe slug for the downloaded layer filename. */
export function layerFilename(scenarioName: string): string {
  const slug =
    scenarioName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "plan";
  return `${slug}-layer.json`;
}
